platform:ios,'7.0'
inhibit_all_warnings!

target "WebIBC" do

pod 'Masonry'
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'UITableView+FDTemplateLayoutCell'
pod 'WebViewJavascriptBridge', '~> 5.0'

end
